CREATE DATABASE IF NOT EXISTS droid64;

CREATE USER 'droid64'@'localhost' IDENTIFIED BY 'uridium';
GRANT ALL PRIVILEGES ON droid64.* TO 'droid64'@'localhost' WITH GRANT OPTION;

CREATE TABLE IF NOT EXISTS disk (
  diskid INTEGER(11) NOT NULL AUTO_INCREMENT,
  filepath VARCHAR(500) NOT NULL,
  filename VARCHAR(100) NOT NULL,
  label VARCHAR(32) DEFAULT NULL,
  updated TIMESTAMP NOT NULL,
  PRIMARY KEY (diskid)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS diskfile (
  fileid INTEGER(11) NOT NULL AUTO_INCREMENT,
  diskid INTEGER(11) NOT NULL,
  name VARCHAR(32) NOT NULL,
  filetype INTEGER(1) NOT NULL DEFAULT 1,
  size INTEGER(4) NOT NULL DEFAULT 0,
  filenum INTEGER(4) NOT NULL DEFAULT 0,
  flags INTEGER(4) NOT NULL DEFAULT 0,
  PRIMARY KEY (fileid),
  FOREIGN KEY (diskid) REFERENCES disk(diskid) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=latin1;
